Update docs-page-new.md
UBCSailbot/.github pull request #7
Opened 2022-10-30 05:31 UTC by DFriend01

Part of #4. Updating the new page template.

2022-11-01 02:06 UTC, patrick-5546 requested changes
Arbitrarily choosing this PR to talk about formatting, applies to all issue template PRs
- Can use `<!-- -->` for comments, imo easier to read and works with the vscode comment shortcut and supports multiline comments
- Remove blank space between header and comment so that people don't write stuff there

2022-11-01 02:06 UTC, patrick-5546 commented on .github/ISSUE_TEMPLATE/docs-page-new.md
> +[//]: # (Describe why this issue is being created. What do we want to achieve?)
Can be more specific: why this page should be created

2022-11-01 02:06 UTC, patrick-5546 commented on .github/ISSUE_TEMPLATE/docs-page-new.md
> +    - Page: section/page.md
The reason i put underscores is so that you know you have to replace it, and that you can double click to select it. You can add this to the section description.

2022-11-01 02:06 UTC, patrick-5546 commented on .github/ISSUE_TEMPLATE/docs-page-new.md
> +[//]: # (What are some topics that will be discussed on the new page?)
... the topics ... on this page?

2022-11-01 02:06 UTC, patrick-5546 commented on .github/ISSUE_TEMPLATE/docs-page-new.md
> +[//]: # (Link to any extra resources that might help with writing the new page.)
See https://github.com/UBCSailbot/.github/pull/6#discussion_r1010006890

2022-11-04 04:29 UTC, DFriend01 commented on .github/ISSUE_TEMPLATE/docs-page-new.md
> +    - Page: section/page.md
My bad, I removed this by accident when I was doing search and replace.

2022-11-04 04:31 UTC, closed without merging