Update docs-page-update.md
UBCSailbot/.github pull request #8
Opened 2022-10-30 05:43 UTC by DFriend01

Related to #4. Updating docs update page.

2022-10-30 07:36 UTC, patrick-5546 reviewed
Do we want section descriptions be rendered or not? If not, we can convert them to markdown comments.

```markdown
<!-- this is a markdown comment -->
```

2022-10-30 23:36 UTC, DFriend01 commented
Prompts are commented out.

2022-11-01 02:06 UTC, patrick-5546 requested changes

2022-11-01 02:06 UTC, patrick-5546 commented on .github/ISSUE_TEMPLATE/docs-page-update.md
> +[//]: # (Why is this issue being created? What is hoped to be achieved by addressing this issue?)
Can be more specific: why does this page need to be updated?

2022-11-01 02:06 UTC, patrick-5546 commented on .github/ISSUE_TEMPLATE/docs-page-update.md
> +[//]: # (Link to any extra resources that could help with updating the docs page.)
See https://github.com/UBCSailbot/.github/pull/6#discussion_r1010006890

2022-11-04 04:25 UTC, closed without merging